### ISSUE TITLE
Not found. Authentication passthru.

### ISSUE THREAD

**Issue by Hareramrai** [zquestz/omniauth-google-oauth2#145]
Hi 

I am getting "Not found. Authentication passthru." , when clicking on this link http://localhost:3000/users/auth/google_oauth2 . 

Below is the server console log details.

``` ruby
Started GET "/users/auth/google_oauth2" for 127.0.0.1 at 2014-09-10 08:54:55 +0530
Processing by Users::OmniauthCallbacksController#passthru as HTML
  Parameters: {"provider"=>"google_oauth2"}
  Rendered text template (0.0ms)
Completed 404 Not Found in 1.7ms (Views: 1.1ms | ActiveRecord: 0.0ms)
```

Can anyone will guide to solve this issue. 

I am using rails 3.2.16 and ruby 2.0

**Comment by vijayj** [comment]
@zquestz - I encountered this issue as well. Turns out I was adding omniauth.rb in the initializers. I am using devise and it turns out that I should not add the omniauth.rb initializers as clearly mentioned in the [Omniauth Overview docs](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview)

**Comment by blairg23** [comment]
@vijayj Does this still pertain to the part in the [Omniauth Overview docs](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview) where it tells you to use that file to [Fix protocol mismatch for redirect uri in Rails](https://github.com/zquestz/omniauth-google-oauth2#fixing-protocol-mismatch-for-redirect_uri-in-rails)? I thought it was only regarding the actual [Usage configuration](https://github.com/zquestz/omniauth-google-oauth2#usage) if you use Devise instead of manually setting routes and controllers.

**Comment by atayl16** [comment]
If anyone comes behind, for me the issue was that I was missing the 1.9.1 in my gemfile. Adding that fixed the issue for me. I spent hours checking my code for typos, but it was the gem all along.

gem "omniauth", "~> 1.9.1" 
gem "omniauth-google-oauth2"

**Comment by aquadrehz** [comment]
@atayl16 
I got the same issue and fixed by your solution.
So I'll leave some detail for someone got the same issue or fix those libs here
FYI

```
  gem 'rails',                      '6.0.3.5'
  gem 'devise',                     '4.7.3',    github: 'heartcombo/devise'
  gem 'omniauth',                   '1.9.1'     # downgrade from '2.0.4'
  gem 'omniauth-google-oauth2',     '0.8.2'     # downgrade from '1.0.0'
```
