### ISSUE TITLE
Can't authenticate with Android app because of missing id_token

### ISSUE THREAD

**Issue by snovity** [zquestz/omniauth-google-oauth2#148]
Android lib converts authentication `code` to tokens on the front-end and exposes only `access_token` for futher usage. The backend gem, on the other hand, besides `access_token` also requires `id_token`. Apparently `id_token` is used only to check if `client_id` matches, and then it is droped and only `access_token` is used.

So the question is:
Is it possible to drop this check for `client_id` and use just `access_token`? Or maybe it is a bad practice and Android app should send authentication `code` as in Hybrid Authentication?

**Comment by poojapalhade** [comment]
hiii guys
i m facing error while accessing tooglr tasks using oauth2

{ "error": {  "errors": [   {    "domain": "usageLimits",    "reason": "accessNotConfigured",    "message": "Access Not Configured. The API (Tasks API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",    "extendedHelp": "https://console.developers.google.com"   }  ],  "code": 403,  "message": "Access Not Configured. The API (Tasks API) is not enabled for your project. Please use the Google Developers Console to update your configuration." }}

Please suggest any solution.
I have enables
1. task api
2. google plus api
3. contact api

**Comment by trupin** [comment]
Hi guys,

I made a small PR (https://github.com/zquestz/omniauth-google-oauth2/pull/165) which permit to an an installed application to login with omniauth. The correct process to do so is in my opinion the one described here: https://developers.google.com/+/web/signin/server-side-flow (see the first diagram).

Here's how I did to make my android application authenticate with omniauth + google:
1 -> the installed application get the authorization code from google with the g+ sdk
2 -> the installed application calls the omniauth callback with the authorization code and the proper redirect_uri (the one associated to the installed app in google dev console).
3 -> omniauth get the access token from google with the authorization code, secret id, application id, and the installed application redirect_uri (if you use the web application one, it will fail with a redirect_uri_mismatch error, that's actually what I fixed in the PR).
4 ->  omniauth does whatever it wants with the access_token, creates a valid session and gives it to your application as a response to the callback request.

That way you can use the same endpoint with the same process for any kind of application (web application and installed applications).

What do you think ?

**Comment by zquestz** [comment]
This should no longer be an issue. Let me know if it is and I can reopen.
