### ISSUE TITLE
omniauth-google-oauth2 vs. google-auth-library-ruby ?

### ISSUE THREAD

**Issue by hundsim** [zquestz/omniauth-google-oauth2#239]
Sorry, I'm a bit confused  - but what's the difference between this gem and Google's own gem google-auth-library-ruby?

If I'd like to use omniauth-google-oauth2 toghether with [the official guidelines](https://developers.google.com/identity/protocols/OAuth2WebServer), is it a good match? All the guides I've seen using omniauth-google-oauth2, seem to use another (older?) API syntax.

**Comment by zquestz** [comment]
@hundsim so the official library from google is a standalone implementation not designed to be used with omniauth or devise, and is still in alpha. If you are looking to support multiple OAuth providers (google, facebook, etc), then you should use this solution instead of googles. This library is still actively maintained and used by lots of users to implement Google Auth.

If you have any questions, I am happy to help out, and the README.md is current with examples that are known to work, so should address your initial set of questions.
