### ISSUE TITLE
Which parameter to pass for mobile logins (id_token)?

### ISSUE THREAD

**Issue by ened** [zquestz/omniauth-google-oauth2#271]
According to this documentation https://developers.google.com/identity/sign-in/ios/backend-auth, the backend server should verify and parse the ID token. Google says:

> To do so securely, after a user successfully signs in, send the user's ID token to your server using HTTPS. Then, on the server, verify the integrity of the ID token and retrieve the user's ID from the sub claim of the ID token.

I'm not sure if the current version of this gem supports this?

We might need to implement: https://github.com/google/google-api-ruby-client/blob/e13da8e05e2368421519e49d2c03ee7e69f3faaa/generated/google/apis/oauth2_v2/service.rb

**Comment by AlexVPopov** [comment]
This is something, I am currently struggling with. So I expected the following flow:

* Andoid app prompts user for authentication;
* User gives permissions;
* Android app receives the authentication hash, that is otherwise received via `request.env["omniauth.auth"]`.
* Android app makes a call to the Rails back-end and includes the `request.env["omniauth.auth"]['credentials']['token']`.

It appears, however, that this method is considered insecure and a migration guide towards passing idToken is provided: https://developers.google.com/identity/sign-in/android/migration-guide

**Comment by ened** [comment]
Similar thing here, yet I'm on iOS and *already received* the ID Token from Google. It's ready to be sent to the server (& the omniauth endpoint).

**Comment by ened** [comment]
Found this and running tests: https://github.com/google/google-id-token

**Comment by ened** [comment]
The linked project (google-id-token) is helpful. The ID token submitted could be decrypted, and `omniauth-google-oauth2` could then extract the email address of a user. It might not contain the users' full name.

**Comment by AlexVPopov** [comment]
@ened Is the user's email sufficient to make a call to Google and fetch the info you need? I thought you need a token, which in omniauth is called `access_token` and in the auth_hash is contained under `auth_hash['credentials']['token']`.

**Comment by zquestz** [comment]
Currently this gem supports getting the `code` param via an XHR request, the `code` param and `redirect_uri` for a normal request, or an `access_token` param. I am pretty sure you should have code or access_token after the login from your Android app.

**Comment by zquestz** [comment]
Closing as I believe this has been answered. Feel free to reopen if you have any other questions.

**Comment by eugenio1590** [comment]
@zquestz I am not quite sure how to send the token to the final point. You could place an example of it. Thanks.
