### ISSUE TITLE
Google Contacts API vs Google People API

### ISSUE THREAD

**Issue by felbalart** [zquestz/omniauth-google-oauth2#321]
The README says to authorize Google's **Contacts API**, which in the Developer's Console indicates:

> This API is no longer being developed further. Please consider migrating to the **People API** instead.

I propose updating the README with Google People API, if everything works using this API instead

In case it doesn't (and Contacts API must be used inevitably), it would be good to put into the README a note to ignore Google's warning

**Comment by zquestz** [comment]
Would love a PR with this change. =)

**Comment by Onumis** [comment]
Atm I think you really only need Google+ API enabled to perform authentication.

**Comment by zquestz** [comment]
G+ api is no longer needed or supported.

**Comment by tonycchung** [comment]
Wanted to make a note for others, the `People API` doesn't fully replace the `Contacts API` functionality - notably being able to fetch `other contacts`. This can still only be done via the `Contacts API` - this is important because a lot of the contacts automatically created for you by google (via your gmail messages and whatnot) are put into this `other contacts` label/category and can only be fetched from the Contacts API.

https://stackoverflow.com/questions/36386957/google-contacts-api-vs-people-api
