### ISSUE TITLE
Since this weekend I'm getting this error No route matches [GET] "/auth/google_oauth2"

### ISSUE THREAD

**Issue by petervandeput** [zquestz/omniauth-google-oauth2#398]
nothing changed in configuration of application nor in google console configuration.
this happens only on the production server and not on the localhost

Please advice

**Comment by brimchan** [comment]
I had the same problem and I forced ```omniauth``` to ```1.9.1``` in my Gemfile. Seems to work now with ```omniauth-google-oauth2``` (0.8.1)

**Comment by jvalenciag** [comment]
Same here! The @brimchan fix works perfect.

**Comment by otegami** [comment]
I had the same problem. I'm not sure all of you are in the same situation as me.
Please look at this documentation about OmniAuth version 2.0. I hope these comment will help you :)
https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#rails

```
If you are using hyperlinks or buttons styled to redirect to your login route, you should update these to be a submit input or a submit type button wrapped in a form.

```
```ruby
- <a href='/auth/developer'>Login with Developer</a>
+ <%= form_tag('/auth/developer', method: 'post') do %>
+  <button type='submit'>Login with Developer</button>
+ <% end %>
```

**Comment by Workman** [comment]
@brimchan's suggestion worked for me. 

I've been having this issue since upgrading to 1.0.0 (omniauth >2) and had to downgrade to make it work as expected. It's like devise cannot find the provider after updating to omniauth 2. 

Specifically whenever I load the google auth path, `request.env['omniauth.params']` is blank and the `passthru` action loads instead of redirecting to the Google login. The page body was “Not found. Authentication passthru”. It's not a `omniauth-google-oauth2` issue, but I'm still unable to track down exactly what needs to change. 

Any ideas as to what changed here?

**Comment by camaeel** [comment]
@zquestz why this issue is closed? This gem in version 1.0.0 doesn't correctly work with devise.

**Comment by zquestz** [comment]
> @zquestz why this issue is closed? This gem in version 1.0.0 doesn't correctly work with devise.

There is nothing in this gem that broke, the issue is on the devise side to support omniauth 2.0. This has nothing to do with specifics in this gem.

**Comment by bogdanRada** [comment]
hi @camaeel. I was facing same issue , but this helped https://github.com/heartcombo/devise/issues/5236 . Read the comments there , that might help you too.

**Comment by camaeel** [comment]
Thank you @bogdanRada  @zquestz I finally managed to set it up correctly yesterday. I think it was probably caused by directly accessing /auth/users/google_oauth2 endpoint (with get), instead of using another page with the link. 
This is a bit problematic as I just wanted to do a simple redirect to this page for a seamless access to my app.
