### ISSUE TITLE
Omniauth 2 causes a redirect_uri_mismatch when a script_name is set

### ISSUE THREAD

**Issue by jhottenstein** [zquestz/omniauth-google-oauth2#401]
Omniauth 2 now includes script_name in the callback_path (https://github.com/omniauth/omniauth/commit/c606a00798a7f516c37c67a708864f9a3eb9f796#diff-c2f37e7010d83348d856f2e436efbfc2a93e396b200d1f6f8821ced735463ce8R437) so the redirect_uri now includes the script_name twice.

This resulted in the following redirect and error:

Response header:
- Location: `https://accounts.google.com/o/oauth2/auth?access_type=online&client_id=<client_id>&hd=<our domain>&prompt=select_account&redirect_uri=http%3A%2F%2Flocalhost%3A4100%2Fadmin%2Fadmin%2Fauth%2Fgoogle_oauth2%2Fcallback&response_type=code&scope=email&state=<state>`

Error 400: redirect_uri_mismatch
The redirect URI in the request, http://localhost:4100/admin/admin/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client.

We monkeypatched OmniAuth::Strategies::GoogleOauth2#callback_url to remove the script_name but I'm not sure that's the best solution if you are trying to support omniauth 1 and 2.

**Comment by koshilife** [comment]
Hi @jhottenstein,

I’m maintainer of some OmniAuth Strategies such as Zoom, Calendly and TimeTree.
Recently our strategies support OmniAuth 2.0 series and refered to [the Upgrading guide](https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0) and [omniauth-github PR](https://github.com/omniauth/omniauth-github/pull/95).

I made a branch for supporting omniauth 2.0 series, it might be fix your errors.
If you want to try my branch, you can use like following in Gemfile.

```rb
gem 'omniauth-google-oauth2', git: "https://github.com/koshilife/omniauth-google-oauth2.git", branch: "allow-for-omniauth-2.0"
```

I suggest this library will release 2 versions for correspond to OmniAuth 1.x and 2.0 series, because of the behavior has changed from OmniAuth 2.0 series as you said.

to be specific
  - At first PR #396 merge and release as 0.8.2 (next version)  for omniauth 1.x support version.
  - Then my branch merge and release as 1.0.0 for omniauth 2.0 series support version.

**Comment by zquestz** [comment]
Seems reasonable to me. Looking forward to seeing the PR.

**Comment by koshilife** [comment]
Hi @zquestz,

I opened #403. Could you check?

**Comment by zquestz** [comment]
PR looked good, will be cutting 2 releases today. The last one for Omniauth 1.x and then a version bumped one for omniauth 2.x.
